name: "Redis"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "cachix/install-nix-action@v31"

      - name: "Configure Devenv Cache"
        uses: "cachix/cachix-action@v16"
        with:
          name: devenv

      - name: "Install Devenv"
        run: nix profile add nixpkgs#devenv

      - name: "Check Redis Compatibility"
        shell: devenv shell bash -- -e {0}
        run: |
          redis-server --save "" --appendonly no --daemonize yes
          for i in {1..10}; do redis-cli ping && break; sleep 1; done
          pytest test/e2e/*
