name: "Redis"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Flox"
        uses: "flox/install-flox-action@v2"

      - name: "Spawn Server"
        uses: "flox/activate-action@v1"
        with:
          command: redis-server &

      - name: "Check Redis Compatiblity"
        uses: "flox/activate-action@v1"
        with:
          command: pytest test/e2e/*
