name: "Redis"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "cachix/install-nix-action@v31"

      - name: "Install Devenv"
        uses: "cachix/devenv@v1"

      - name: "Check Redis Compatibility"
        run: |
          devenv shell bash -lc '
            redis-server --save "" --appendonly no --daemonize yes
            for i in {1..10}; do redis-cli ping && break; sleep 1; done
            pytest test/e2e/*
          '
